version: '2.3'

networks:
  ros:
    driver: bridge

services:

  ros-master:
    image: ros:melodic-ros-core
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  ros-odometry:
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    container_name: odometry
    networks:
      - ros
    ports:
      - "7776:22" # SSH
      - "7777:7777" # GDB Server
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - ${HOME}/.Xauthority:/home/dev/.Xauthority:rw # X11 stuff
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # X11 stuff
      - /dev/dri:/dev/dri #X11 stuff
      - /dev/snd:/dev/snd #X11 stuff
      - /data:/data #
      - /home/andy:/home/andy:rw

  ros-viz:
    image: osrf/ros:melodic-desktop-full
    container_name: ros_visualizer
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros_visualizer"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    #share user in order to access your x11
    user: 1000:1000 #adapt as needed!
    volumes:
      #share your x11 socket and permissions
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/andy:/home/andy:rw
    command: rviz