version: '2.3'

networks:
  ros:
    driver: bridge

services:

  master:
    image: ros:melodic-ros-core
    container_name: master
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  odometry:
    build:
      context: .
      dockerfile: Dockerfile_odometry
    container_name: odometry
    depends_on:
        - master
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - ros
    ports:
      - "7776:22" # SSH
      - "7777:7777" # GDB Server
    environment:
      - "ROS_MASTER_URI=http://master:11311"
      - "ROS_HOSTNAME=odometry"
      - "ROS_ROOT=/opt/ros/melodic/share/ros"
      - "ROS_PACKAGE_PATH=/opt/ros/melodic/share"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - ${HOME}/.Xauthority:/home/dev/.Xauthority:rw # X11 stuff
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # X11 stuff
      - /dev/dri:/dev/dri #X11 stuff
      - /dev/snd:/dev/snd #X11 stuff
      - /data:/data #
      - /home/andy:/home/andy:rw
    restart: always

  vizualizer:
    build:
      context: .
      dockerfile: Dockerfile_visualizer
    container_name: visualizer
    depends_on:
      - master
    networks:
      - ros
    runtime: nvidia
    environment:
      - "ROS_MASTER_URI=http://master:11311"
      - "ROS_HOSTNAME=visualizer"
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    #share user in order to access your x11
    user: 1000:1000 #adapt as needed!
    volumes:
      #share your x11 socket and permissions
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/andy:/home/andy:rw
    restart: always
    command: rviz